server.port=8080

# Database Configuration
spring.datasource.base.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/db_medlink
spring.datasource.name=db_medlink
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.schema=public

# Disable JPA completamente (projeto usa JDBC puro)
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

# JWT Configuration
jwt.secret=bWVkbGlua2p3dHNlY3JldGtleWZvcmF1dGhlbnRpY2F0aW9uYW5kYXV0aG9yaXphdGlvbjIwMjQ=
jwt.expiration=86400000

# Active Profile
spring.profiles.active=jwt

# Allow bean definition overriding
spring.main.allow-bean-definition-overriding=true
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER
