server.port=8080

# Database Configuration
spring.datasource.base.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/db_medlink
spring.datasource.name=db_medlink
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.schema=public

# Disable JPA completamente (projeto usa JDBC puro)
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
