spring.application.name=medlink
server.port=8080

spring.datasource.name=db_medlink
spring.datasource.base.url=jdbc:postgresql://localhost:5432/
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.datasource.name}
spring.datasource.username=postgres
spring.datasource.password=pikachu
spring.datasource.driver-class-name=org.postgresql.Driver



# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000

# Logging Configuration
logging.level.br.fai.lds.medlink=DEBUG
logging.level.org.springframework.web=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Jackson Date Configuration
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=America/Sao_Paulo
